"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  Layout,
  Plus,
  Trash2,
  Edit2,
  FileText,
  Import,
  ChevronDown,
} from "lucide-react";
import { toast } from "sonner";
import { useAppStore } from "@/stores/useAppStore";
import { formatDate } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { AppShell } from "@/components/app-shell";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import {
  RESUME_TEMPLATE_IDS,
  RESUME_TEMPLATE_LABELS,
} from "@/lib/resume-template-styles";
import { getBuiltInTemplateAsCustom } from "@/lib/built-in-templates";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import type { ResumeTemplate } from "@/lib/types";

export default function TemplatesPage() {
  const router = useRouter();
  const customTemplates = useAppStore((s) => s.customTemplates);
  const addTemplate = useAppStore((s) => s.addTemplate);
  const importCustomTemplate = useAppStore((s) => s.importCustomTemplate);
  const removeTemplate = useAppStore((s) => s.removeTemplate);
  const [loading, setLoading] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [importValue, setImportValue] = useState("");

  const onCreate = async (baseId?: ResumeTemplate) => {
    setLoading(true);
    try {
      let t;
      if (baseId) {
        const data = getBuiltInTemplateAsCustom(baseId);
        t = await importCustomTemplate(data);
      } else {
        t = await addTemplate("New Template");
      }
      router.push(`/templates/${t.id}`);
    } catch (e) {
      toast.error("Failed to create template");
    } finally {
      setLoading(false);
    }
  };

  const onImport = async () => {
    if (!importValue.trim()) return;
    setLoading(true);
    try {
      const data = JSON.parse(importValue);
      // Basic validation
      if (!data.name || !data.nodes || !data.nodes.h1 || !data.nodes.page) {
        throw new Error("Invalid template format. Missing required nodes.");
      }
      const t = await importCustomTemplate(data);
      toast.success("Template imported");
      setImportOpen(false);
      setImportValue("");
      router.push(`/templates/${t.id}`);
    } catch (e) {
      toast.error(
        e instanceof Error
          ? e.message
          : "Failed to import template. Ensure valid JSON."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <AppShell>
      <div className="flex flex-1 flex-col gap-4 p-6 overflow-auto">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div>
            <h1 className="text-xl font-semibold tracking-tight text-foreground">
              Custom Templates
            </h1>
            <p className="text-sm text-muted-foreground">
              Build and manage your own resume layouts with custom HTML and CSS.
            </p>
          </div>
          <div className="flex gap-2">
            <Dialog open={importOpen} onOpenChange={setImportOpen}>
              <DialogTrigger asChild>
                <Button variant="outline" className="cursor-pointer gap-2">
                  <Import className="h-4 w-4" />
                  Import JSON
                </Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-xl text-foreground">
                <DialogHeader>
                  <DialogTitle>Import Template</DialogTitle>
                  <DialogDescription>
                    Paste the JSON generated by AI to create a template
                    instantly.
                  </DialogDescription>
                </DialogHeader>
                <div className="py-2">
                  <Textarea
                    placeholder='{ &quot;name&quot;: &quot;...&quot;, &quot;nodes&quot;: { ... } }'
                    className="min-h-[300px] font-mono text-xs"
                    value={importValue}
                    onChange={(e) => setImportValue(e.target.value)}
                  />
                </div>
                <DialogFooter>
                  <Button
                    variant="secondary"
                    onClick={() => setImportOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button onClick={() => void onImport()} disabled={loading}>
                    Import
                  </Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>

            <div className="flex rounded-md shadow-sm">
              <Button
                type="button"
                className="cursor-pointer gap-2 rounded-r-none border-r border-primary-foreground/20"
                onClick={() => void onCreate()}
                disabled={loading}
              >
                <Plus className="h-4 w-4" />
                New Template
              </Button>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    type="button"
                    className="cursor-pointer px-2 rounded-l-none"
                    disabled={loading}
                  >
                    <ChevronDown className="h-4 w-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-48">
                  <div className="px-2 py-1.5 text-[10px] uppercase font-bold text-muted-foreground tracking-wider">
                    New from built-in
                  </div>
                  {RESUME_TEMPLATE_IDS.map((id) => (
                    <DropdownMenuItem
                      key={id}
                      className="cursor-pointer"
                      onClick={() => void onCreate(id)}
                    >
                      {RESUME_TEMPLATE_LABELS[id]}
                    </DropdownMenuItem>
                  ))}
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {customTemplates.map((t) => (
            <Card key={t.id} className="group transition-shadow hover:shadow-md">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center justify-between">
                  <span className="truncate">{t.name}</span>
                  <Layout className="h-4 w-4 text-muted-foreground opacity-50" />
                </CardTitle>
                <CardDescription className="text-xs">
                  Updated {formatDate(t.updatedAt)}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex gap-2">
                  <Button
                    asChild
                    variant="secondary"
                    size="sm"
                    className="flex-1 cursor-pointer gap-1"
                  >
                    <Link href={`/templates/${t.id}`}>
                      <Edit2 className="h-3.5 w-3.5" />
                      Edit
                    </Link>
                  </Button>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    className="cursor-pointer text-destructive hover:text-destructive hover:bg-destructive/10"
                    onClick={() => {
                      if (confirm("Are you sure you want to delete this template?")) {
                        void removeTemplate(t.id);
                        toast.success("Template deleted");
                      }
                    }}
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}

          {customTemplates.length === 0 && (
            <Card className="border-dashed flex flex-col items-center justify-center p-8 text-center sm:col-span-2 lg:col-span-3 xl:col-span-4">
              <div className="h-12 w-12 rounded-full bg-secondary/50 flex items-center justify-center mb-4">
                <Layout className="h-6 w-6 text-muted-foreground" />
              </div>
              <h3 className="text-lg font-medium">No custom templates yet</h3>
              <p className="text-sm text-muted-foreground mb-6 max-w-sm">
                Create your first template to start customizing your resume layouts with raw HTML and inline CSS.
              </p>
              <Button
                variant="outline"
                className="cursor-pointer gap-2"
                onClick={() => void onCreate()}
                disabled={loading}
              >
                <Plus className="h-4 w-4" />
                Create Template
              </Button>
            </Card>
          )}
        </div>
      </div>
    </AppShell>
  );
}
